# -*- coding: utf-8 -*-
"""Monte Carlo find pi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PtOixQPusXx7J5-Og9ox_u9Rvhd4Ej-5
"""

import random as r
import math as m
import matplotlib.pyplot as plt

count = 0
titik = 1000
x=[]
y=[]
xin = []
yin = []
xout = []
yout = []
t = 0
for i in range(0, titik):

  x.append((2 * r.random()) - 1)
  y.append((2 * r.random()) - 1)
  luas = (x[t] * x[t]) + (y[t] * y[t])
  if luas < 1.0:
    xin.append(x[t])
    yin.append(y[t])
    count += 1
  else :
    xout.append(x[t])
    yout.append(y[t])
  t+=1

crc = plt.Circle((0, 0), 1, color='red')
fig, ax = plt.subplots()
ax.add_artist(crc)
phi = (count / titik) * 4
plt.plot(xin,yin,'o',xout,yout,'o')
plt.show()


print('pi = ', phi)